/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AreaTeRouteImport } from './routes/area-te'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ComunicadosRouteImport } from './routes/comunicados'
import { Route as ContatosRouteImport } from './routes/contatos'
import { Route as FerramentasRouteImport } from './routes/ferramentas'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as ApiUploadRouteImport } from './routes/api/upload'
import { Route as AreaTeIndexRouteImport } from './routes/area-te.index'
import { Route as AreaTeComunicadosRouteImport } from './routes/area-te.comunicados'
import { Route as AreaTeContatosRouteImport } from './routes/area-te.contatos'
import { Route as AreaTeFerramentasRouteImport } from './routes/area-te.ferramentas'
import { Route as AreaTePerfilRouteImport } from './routes/area-te.perfil'
import { Route as AreaTeSolicitacoesRouteImport } from './routes/area-te.solicitacoes'
import { Route as AreaTeTiposSolicitacaoRouteImport } from './routes/area-te.tipos-solicitacao'
import { Route as AreaTeUnidadesRouteImport } from './routes/area-te.unidades'
import { Route as AreaTeUsuariosRouteImport } from './routes/area-te.usuarios'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as SolicitacoesIndexRouteImport } from './routes/solicitacoes.index'
import { Route as SolicitacoesSlugRouteImport } from './routes/solicitacoes.$slug'
import { Route as ApiAuthGoogleRouteImport } from './routes/api/auth.google'
import { Route as ApiFilesSplatRouteImport } from './routes/api/files.$'
import { Route as AreaTeSolicitacoesIdRouteImport } from './routes/area-te.solicitacoes.$id'
import { Route as AreaTeTiposSolicitacaoIdRouteImport } from './routes/area-te.tipos-solicitacao.$id'
import { Route as AreaTeUnidadesIdRouteImport } from './routes/area-te.unidades.$id'
import { Route as ApiAuthGoogleCallbackRouteImport } from './routes/api/auth.google.callback'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AreaTeRoute = AreaTeRouteImport.update({
  id: '/area-te',
  path: '/area-te',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ComunicadosRoute = ComunicadosRouteImport.update({
  id: '/comunicados',
  path: '/comunicados',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatosRoute = ContatosRouteImport.update({
  id: '/contatos',
  path: '/contatos',
  getParentRoute: () => rootRouteImport,
} as any)
const FerramentasRoute = FerramentasRouteImport.update({
  id: '/ferramentas',
  path: '/ferramentas',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadRoute = ApiUploadRouteImport.update({
  id: '/api/upload',
  path: '/api/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const AreaTeIndexRoute = AreaTeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AreaTeRoute,
} as any)
const AreaTeComunicadosRoute = AreaTeComunicadosRouteImport.update({
  id: '/comunicados',
  path: '/comunicados',
  getParentRoute: () => AreaTeRoute,
} as any)
const AreaTeContatosRoute = AreaTeContatosRouteImport.update({
  id: '/contatos',
  path: '/contatos',
  getParentRoute: () => AreaTeRoute,
} as any)
const AreaTeFerramentasRoute = AreaTeFerramentasRouteImport.update({
  id: '/ferramentas',
  path: '/ferramentas',
  getParentRoute: () => AreaTeRoute,
} as any)
const AreaTePerfilRoute = AreaTePerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AreaTeRoute,
} as any)
const AreaTeSolicitacoesRoute = AreaTeSolicitacoesRouteImport.update({
  id: '/solicitacoes',
  path: '/solicitacoes',
  getParentRoute: () => AreaTeRoute,
} as any)
const AreaTeTiposSolicitacaoRoute = AreaTeTiposSolicitacaoRouteImport.update({
  id: '/tipos-solicitacao',
  path: '/tipos-solicitacao',
  getParentRoute: () => AreaTeRoute,
} as any)
const AreaTeUnidadesRoute = AreaTeUnidadesRouteImport.update({
  id: '/unidades',
  path: '/unidades',
  getParentRoute: () => AreaTeRoute,
} as any)
const AreaTeUsuariosRoute = AreaTeUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AreaTeRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => AuthRoute,
} as any)
const SolicitacoesIndexRoute = SolicitacoesIndexRouteImport.update({
  id: '/solicitacoes/',
  path: '/solicitacoes/',
  getParentRoute: () => rootRouteImport,
} as any)
const SolicitacoesSlugRoute = SolicitacoesSlugRouteImport.update({
  id: '/solicitacoes/$slug',
  path: '/solicitacoes/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthGoogleRoute = ApiAuthGoogleRouteImport.update({
  id: '/api/auth/google',
  path: '/api/auth/google',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFilesSplatRoute = ApiFilesSplatRouteImport.update({
  id: '/api/files/$',
  path: '/api/files/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AreaTeSolicitacoesIdRoute = AreaTeSolicitacoesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AreaTeSolicitacoesRoute,
} as any)
const AreaTeTiposSolicitacaoIdRoute =
  AreaTeTiposSolicitacaoIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AreaTeTiposSolicitacaoRoute,
  } as any)
const AreaTeUnidadesIdRoute = AreaTeUnidadesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AreaTeUnidadesRoute,
} as any)
const ApiAuthGoogleCallbackRoute = ApiAuthGoogleCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => ApiAuthGoogleRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/area-te': typeof AreaTeRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/comunicados': typeof ComunicadosRoute
  '/contatos': typeof ContatosRoute
  '/ferramentas': typeof FerramentasRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sobre': typeof SobreRoute
  '/api/upload': typeof ApiUploadRoute
  '/area-te/comunicados': typeof AreaTeComunicadosRoute
  '/area-te/contatos': typeof AreaTeContatosRoute
  '/area-te/ferramentas': typeof AreaTeFerramentasRoute
  '/area-te/perfil': typeof AreaTePerfilRoute
  '/area-te/solicitacoes': typeof AreaTeSolicitacoesRouteWithChildren
  '/area-te/tipos-solicitacao': typeof AreaTeTiposSolicitacaoRouteWithChildren
  '/area-te/unidades': typeof AreaTeUnidadesRouteWithChildren
  '/area-te/usuarios': typeof AreaTeUsuariosRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/solicitacoes/$slug': typeof SolicitacoesSlugRoute
  '/area-te/': typeof AreaTeIndexRoute
  '/solicitacoes/': typeof SolicitacoesIndexRoute
  '/api/auth/google': typeof ApiAuthGoogleRouteWithChildren
  '/api/files/$': typeof ApiFilesSplatRoute
  '/area-te/solicitacoes/$id': typeof AreaTeSolicitacoesIdRoute
  '/area-te/tipos-solicitacao/$id': typeof AreaTeTiposSolicitacaoIdRoute
  '/area-te/unidades/$id': typeof AreaTeUnidadesIdRoute
  '/api/auth/google/callback': typeof ApiAuthGoogleCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/comunicados': typeof ComunicadosRoute
  '/contatos': typeof ContatosRoute
  '/ferramentas': typeof FerramentasRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sobre': typeof SobreRoute
  '/api/upload': typeof ApiUploadRoute
  '/area-te/comunicados': typeof AreaTeComunicadosRoute
  '/area-te/contatos': typeof AreaTeContatosRoute
  '/area-te/ferramentas': typeof AreaTeFerramentasRoute
  '/area-te/perfil': typeof AreaTePerfilRoute
  '/area-te/solicitacoes': typeof AreaTeSolicitacoesRouteWithChildren
  '/area-te/tipos-solicitacao': typeof AreaTeTiposSolicitacaoRouteWithChildren
  '/area-te/unidades': typeof AreaTeUnidadesRouteWithChildren
  '/area-te/usuarios': typeof AreaTeUsuariosRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/solicitacoes/$slug': typeof SolicitacoesSlugRoute
  '/area-te': typeof AreaTeIndexRoute
  '/solicitacoes': typeof SolicitacoesIndexRoute
  '/api/auth/google': typeof ApiAuthGoogleRouteWithChildren
  '/api/files/$': typeof ApiFilesSplatRoute
  '/area-te/solicitacoes/$id': typeof AreaTeSolicitacoesIdRoute
  '/area-te/tipos-solicitacao/$id': typeof AreaTeTiposSolicitacaoIdRoute
  '/area-te/unidades/$id': typeof AreaTeUnidadesIdRoute
  '/api/auth/google/callback': typeof ApiAuthGoogleCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/area-te': typeof AreaTeRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/comunicados': typeof ComunicadosRoute
  '/contatos': typeof ContatosRoute
  '/ferramentas': typeof FerramentasRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sobre': typeof SobreRoute
  '/api/upload': typeof ApiUploadRoute
  '/area-te/comunicados': typeof AreaTeComunicadosRoute
  '/area-te/contatos': typeof AreaTeContatosRoute
  '/area-te/ferramentas': typeof AreaTeFerramentasRoute
  '/area-te/perfil': typeof AreaTePerfilRoute
  '/area-te/solicitacoes': typeof AreaTeSolicitacoesRouteWithChildren
  '/area-te/tipos-solicitacao': typeof AreaTeTiposSolicitacaoRouteWithChildren
  '/area-te/unidades': typeof AreaTeUnidadesRouteWithChildren
  '/area-te/usuarios': typeof AreaTeUsuariosRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/solicitacoes/$slug': typeof SolicitacoesSlugRoute
  '/area-te/': typeof AreaTeIndexRoute
  '/solicitacoes/': typeof SolicitacoesIndexRoute
  '/api/auth/google': typeof ApiAuthGoogleRouteWithChildren
  '/api/files/$': typeof ApiFilesSplatRoute
  '/area-te/solicitacoes/$id': typeof AreaTeSolicitacoesIdRoute
  '/area-te/tipos-solicitacao/$id': typeof AreaTeTiposSolicitacaoIdRoute
  '/area-te/unidades/$id': typeof AreaTeUnidadesIdRoute
  '/api/auth/google/callback': typeof ApiAuthGoogleCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/area-te'
    | '/auth'
    | '/comunicados'
    | '/contatos'
    | '/ferramentas'
    | '/forgot-password'
    | '/reset-password'
    | '/sobre'
    | '/api/upload'
    | '/area-te/comunicados'
    | '/area-te/contatos'
    | '/area-te/ferramentas'
    | '/area-te/perfil'
    | '/area-te/solicitacoes'
    | '/area-te/tipos-solicitacao'
    | '/area-te/unidades'
    | '/area-te/usuarios'
    | '/auth/callback'
    | '/solicitacoes/$slug'
    | '/area-te/'
    | '/solicitacoes/'
    | '/api/auth/google'
    | '/api/files/$'
    | '/area-te/solicitacoes/$id'
    | '/area-te/tipos-solicitacao/$id'
    | '/area-te/unidades/$id'
    | '/api/auth/google/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/comunicados'
    | '/contatos'
    | '/ferramentas'
    | '/forgot-password'
    | '/reset-password'
    | '/sobre'
    | '/api/upload'
    | '/area-te/comunicados'
    | '/area-te/contatos'
    | '/area-te/ferramentas'
    | '/area-te/perfil'
    | '/area-te/solicitacoes'
    | '/area-te/tipos-solicitacao'
    | '/area-te/unidades'
    | '/area-te/usuarios'
    | '/auth/callback'
    | '/solicitacoes/$slug'
    | '/area-te'
    | '/solicitacoes'
    | '/api/auth/google'
    | '/api/files/$'
    | '/area-te/solicitacoes/$id'
    | '/area-te/tipos-solicitacao/$id'
    | '/area-te/unidades/$id'
    | '/api/auth/google/callback'
  id:
    | '__root__'
    | '/'
    | '/area-te'
    | '/auth'
    | '/comunicados'
    | '/contatos'
    | '/ferramentas'
    | '/forgot-password'
    | '/reset-password'
    | '/sobre'
    | '/api/upload'
    | '/area-te/comunicados'
    | '/area-te/contatos'
    | '/area-te/ferramentas'
    | '/area-te/perfil'
    | '/area-te/solicitacoes'
    | '/area-te/tipos-solicitacao'
    | '/area-te/unidades'
    | '/area-te/usuarios'
    | '/auth/callback'
    | '/solicitacoes/$slug'
    | '/area-te/'
    | '/solicitacoes/'
    | '/api/auth/google'
    | '/api/files/$'
    | '/area-te/solicitacoes/$id'
    | '/area-te/tipos-solicitacao/$id'
    | '/area-te/unidades/$id'
    | '/api/auth/google/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AreaTeRoute: typeof AreaTeRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  ComunicadosRoute: typeof ComunicadosRoute
  ContatosRoute: typeof ContatosRoute
  FerramentasRoute: typeof FerramentasRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SobreRoute: typeof SobreRoute
  ApiUploadRoute: typeof ApiUploadRoute
  SolicitacoesSlugRoute: typeof SolicitacoesSlugRoute
  SolicitacoesIndexRoute: typeof SolicitacoesIndexRoute
  ApiAuthGoogleRoute: typeof ApiAuthGoogleRouteWithChildren
  ApiFilesSplatRoute: typeof ApiFilesSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/area-te': {
      id: '/area-te'
      path: '/area-te'
      fullPath: '/area-te'
      preLoaderRoute: typeof AreaTeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comunicados': {
      id: '/comunicados'
      path: '/comunicados'
      fullPath: '/comunicados'
      preLoaderRoute: typeof ComunicadosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contatos': {
      id: '/contatos'
      path: '/contatos'
      fullPath: '/contatos'
      preLoaderRoute: typeof ContatosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ferramentas': {
      id: '/ferramentas'
      path: '/ferramentas'
      fullPath: '/ferramentas'
      preLoaderRoute: typeof FerramentasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/upload': {
      id: '/api/upload'
      path: '/api/upload'
      fullPath: '/api/upload'
      preLoaderRoute: typeof ApiUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/area-te/': {
      id: '/area-te/'
      path: '/'
      fullPath: '/area-te/'
      preLoaderRoute: typeof AreaTeIndexRouteImport
      parentRoute: typeof AreaTeRoute
    }
    '/area-te/comunicados': {
      id: '/area-te/comunicados'
      path: '/comunicados'
      fullPath: '/area-te/comunicados'
      preLoaderRoute: typeof AreaTeComunicadosRouteImport
      parentRoute: typeof AreaTeRoute
    }
    '/area-te/contatos': {
      id: '/area-te/contatos'
      path: '/contatos'
      fullPath: '/area-te/contatos'
      preLoaderRoute: typeof AreaTeContatosRouteImport
      parentRoute: typeof AreaTeRoute
    }
    '/area-te/ferramentas': {
      id: '/area-te/ferramentas'
      path: '/ferramentas'
      fullPath: '/area-te/ferramentas'
      preLoaderRoute: typeof AreaTeFerramentasRouteImport
      parentRoute: typeof AreaTeRoute
    }
    '/area-te/perfil': {
      id: '/area-te/perfil'
      path: '/perfil'
      fullPath: '/area-te/perfil'
      preLoaderRoute: typeof AreaTePerfilRouteImport
      parentRoute: typeof AreaTeRoute
    }
    '/area-te/solicitacoes': {
      id: '/area-te/solicitacoes'
      path: '/solicitacoes'
      fullPath: '/area-te/solicitacoes'
      preLoaderRoute: typeof AreaTeSolicitacoesRouteImport
      parentRoute: typeof AreaTeRoute
    }
    '/area-te/tipos-solicitacao': {
      id: '/area-te/tipos-solicitacao'
      path: '/tipos-solicitacao'
      fullPath: '/area-te/tipos-solicitacao'
      preLoaderRoute: typeof AreaTeTiposSolicitacaoRouteImport
      parentRoute: typeof AreaTeRoute
    }
    '/area-te/unidades': {
      id: '/area-te/unidades'
      path: '/unidades'
      fullPath: '/area-te/unidades'
      preLoaderRoute: typeof AreaTeUnidadesRouteImport
      parentRoute: typeof AreaTeRoute
    }
    '/area-te/usuarios': {
      id: '/area-te/usuarios'
      path: '/usuarios'
      fullPath: '/area-te/usuarios'
      preLoaderRoute: typeof AreaTeUsuariosRouteImport
      parentRoute: typeof AreaTeRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof AuthRoute
    }
    '/solicitacoes/': {
      id: '/solicitacoes/'
      path: '/solicitacoes'
      fullPath: '/solicitacoes/'
      preLoaderRoute: typeof SolicitacoesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solicitacoes/$slug': {
      id: '/solicitacoes/$slug'
      path: '/solicitacoes/$slug'
      fullPath: '/solicitacoes/$slug'
      preLoaderRoute: typeof SolicitacoesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/google': {
      id: '/api/auth/google'
      path: '/api/auth/google'
      fullPath: '/api/auth/google'
      preLoaderRoute: typeof ApiAuthGoogleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/files/$': {
      id: '/api/files/$'
      path: '/api/files/$'
      fullPath: '/api/files/$'
      preLoaderRoute: typeof ApiFilesSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/area-te/solicitacoes/$id': {
      id: '/area-te/solicitacoes/$id'
      path: '/$id'
      fullPath: '/area-te/solicitacoes/$id'
      preLoaderRoute: typeof AreaTeSolicitacoesIdRouteImport
      parentRoute: typeof AreaTeSolicitacoesRoute
    }
    '/area-te/tipos-solicitacao/$id': {
      id: '/area-te/tipos-solicitacao/$id'
      path: '/$id'
      fullPath: '/area-te/tipos-solicitacao/$id'
      preLoaderRoute: typeof AreaTeTiposSolicitacaoIdRouteImport
      parentRoute: typeof AreaTeTiposSolicitacaoRoute
    }
    '/area-te/unidades/$id': {
      id: '/area-te/unidades/$id'
      path: '/$id'
      fullPath: '/area-te/unidades/$id'
      preLoaderRoute: typeof AreaTeUnidadesIdRouteImport
      parentRoute: typeof AreaTeUnidadesRoute
    }
    '/api/auth/google/callback': {
      id: '/api/auth/google/callback'
      path: '/callback'
      fullPath: '/api/auth/google/callback'
      preLoaderRoute: typeof ApiAuthGoogleCallbackRouteImport
      parentRoute: typeof ApiAuthGoogleRoute
    }
  }
}

interface AreaTeSolicitacoesRouteChildren {
  AreaTeSolicitacoesIdRoute: typeof AreaTeSolicitacoesIdRoute
}

const AreaTeSolicitacoesRouteChildren: AreaTeSolicitacoesRouteChildren = {
  AreaTeSolicitacoesIdRoute: AreaTeSolicitacoesIdRoute,
}

const AreaTeSolicitacoesRouteWithChildren =
  AreaTeSolicitacoesRoute._addFileChildren(AreaTeSolicitacoesRouteChildren)

interface AreaTeTiposSolicitacaoRouteChildren {
  AreaTeTiposSolicitacaoIdRoute: typeof AreaTeTiposSolicitacaoIdRoute
}

const AreaTeTiposSolicitacaoRouteChildren: AreaTeTiposSolicitacaoRouteChildren =
  {
    AreaTeTiposSolicitacaoIdRoute: AreaTeTiposSolicitacaoIdRoute,
  }

const AreaTeTiposSolicitacaoRouteWithChildren =
  AreaTeTiposSolicitacaoRoute._addFileChildren(
    AreaTeTiposSolicitacaoRouteChildren,
  )

interface AreaTeUnidadesRouteChildren {
  AreaTeUnidadesIdRoute: typeof AreaTeUnidadesIdRoute
}

const AreaTeUnidadesRouteChildren: AreaTeUnidadesRouteChildren = {
  AreaTeUnidadesIdRoute: AreaTeUnidadesIdRoute,
}

const AreaTeUnidadesRouteWithChildren = AreaTeUnidadesRoute._addFileChildren(
  AreaTeUnidadesRouteChildren,
)

interface AreaTeRouteChildren {
  AreaTeComunicadosRoute: typeof AreaTeComunicadosRoute
  AreaTeContatosRoute: typeof AreaTeContatosRoute
  AreaTeFerramentasRoute: typeof AreaTeFerramentasRoute
  AreaTePerfilRoute: typeof AreaTePerfilRoute
  AreaTeSolicitacoesRoute: typeof AreaTeSolicitacoesRouteWithChildren
  AreaTeTiposSolicitacaoRoute: typeof AreaTeTiposSolicitacaoRouteWithChildren
  AreaTeUnidadesRoute: typeof AreaTeUnidadesRouteWithChildren
  AreaTeUsuariosRoute: typeof AreaTeUsuariosRoute
  AreaTeIndexRoute: typeof AreaTeIndexRoute
}

const AreaTeRouteChildren: AreaTeRouteChildren = {
  AreaTeComunicadosRoute: AreaTeComunicadosRoute,
  AreaTeContatosRoute: AreaTeContatosRoute,
  AreaTeFerramentasRoute: AreaTeFerramentasRoute,
  AreaTePerfilRoute: AreaTePerfilRoute,
  AreaTeSolicitacoesRoute: AreaTeSolicitacoesRouteWithChildren,
  AreaTeTiposSolicitacaoRoute: AreaTeTiposSolicitacaoRouteWithChildren,
  AreaTeUnidadesRoute: AreaTeUnidadesRouteWithChildren,
  AreaTeUsuariosRoute: AreaTeUsuariosRoute,
  AreaTeIndexRoute: AreaTeIndexRoute,
}

const AreaTeRouteWithChildren =
  AreaTeRoute._addFileChildren(AreaTeRouteChildren)

interface AuthRouteChildren {
  AuthCallbackRoute: typeof AuthCallbackRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthCallbackRoute: AuthCallbackRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface ApiAuthGoogleRouteChildren {
  ApiAuthGoogleCallbackRoute: typeof ApiAuthGoogleCallbackRoute
}

const ApiAuthGoogleRouteChildren: ApiAuthGoogleRouteChildren = {
  ApiAuthGoogleCallbackRoute: ApiAuthGoogleCallbackRoute,
}

const ApiAuthGoogleRouteWithChildren = ApiAuthGoogleRoute._addFileChildren(
  ApiAuthGoogleRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AreaTeRoute: AreaTeRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  ComunicadosRoute: ComunicadosRoute,
  ContatosRoute: ContatosRoute,
  FerramentasRoute: FerramentasRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SobreRoute: SobreRoute,
  ApiUploadRoute: ApiUploadRoute,
  SolicitacoesSlugRoute: SolicitacoesSlugRoute,
  SolicitacoesIndexRoute: SolicitacoesIndexRoute,
  ApiAuthGoogleRoute: ApiAuthGoogleRouteWithChildren,
  ApiFilesSplatRoute: ApiFilesSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
