/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as FerramentasRouteImport } from './routes/ferramentas'
import { Route as ComunicadosRouteImport } from './routes/comunicados'
import { Route as IndexRouteImport } from './routes/index'

const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const FerramentasRoute = FerramentasRouteImport.update({
  id: '/ferramentas',
  path: '/ferramentas',
  getParentRoute: () => rootRouteImport,
} as any)
const ComunicadosRoute = ComunicadosRouteImport.update({
  id: '/comunicados',
  path: '/comunicados',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/comunicados': typeof ComunicadosRoute
  '/ferramentas': typeof FerramentasRoute
  '/sobre': typeof SobreRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/comunicados': typeof ComunicadosRoute
  '/ferramentas': typeof FerramentasRoute
  '/sobre': typeof SobreRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/comunicados': typeof ComunicadosRoute
  '/ferramentas': typeof FerramentasRoute
  '/sobre': typeof SobreRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/comunicados' | '/ferramentas' | '/sobre'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/comunicados' | '/ferramentas' | '/sobre'
  id: '__root__' | '/' | '/comunicados' | '/ferramentas' | '/sobre'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ComunicadosRoute: typeof ComunicadosRoute
  FerramentasRoute: typeof FerramentasRoute
  SobreRoute: typeof SobreRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ferramentas': {
      id: '/ferramentas'
      path: '/ferramentas'
      fullPath: '/ferramentas'
      preLoaderRoute: typeof FerramentasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comunicados': {
      id: '/comunicados'
      path: '/comunicados'
      fullPath: '/comunicados'
      preLoaderRoute: typeof ComunicadosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ComunicadosRoute: ComunicadosRoute,
  FerramentasRoute: FerramentasRoute,
  SobreRoute: SobreRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
